// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace VendingMachine.Data
{
    public partial class CoinExtensionsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CoinExtensionsTest))]
public void ToValue832()
{
    decimal d;
    d = this.ToValue(Coin.Ore50);
    Assert.AreEqual<decimal>(5e-1M, d);
}
[TestMethod]
[PexGeneratedBy(typeof(CoinExtensionsTest))]
public void ToValue513()
{
    decimal d;
    d = this.ToValue(Coin.Kr1);
    Assert.AreEqual<decimal>(1M, d);
}
[TestMethod]
[PexGeneratedBy(typeof(CoinExtensionsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ToValueThrowsContractException646()
{
    try
    {
      if (!PexContract.HasRequiredRuntimeContracts
               (typeof(CoinExtensions), (PexRuntimeContractsFlags)28927))
        Assert.Inconclusive
            ("assembly VendingMachine is not instrumented with runtime contracts");
      decimal d;
      d = this.ToValue((Coin)6);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(CoinExtensionsTest))]
public void ToValue1()
{
    decimal d;
    d = this.ToValue(Coin.Kr2);
    Assert.AreEqual<decimal>(2M, d);
}
[TestMethod]
[PexGeneratedBy(typeof(CoinExtensionsTest))]
public void ToValue932()
{
    decimal d;
    d = this.ToValue(Coin.Kr5);
    Assert.AreEqual<decimal>(5M, d);
}
[TestMethod]
[PexGeneratedBy(typeof(CoinExtensionsTest))]
public void ToValue347()
{
    decimal d;
    d = this.ToValue(Coin.Kr10);
    Assert.AreEqual<decimal>(10M, d);
}
[TestMethod]
[PexGeneratedBy(typeof(CoinExtensionsTest))]
public void ToValue66()
{
    decimal d;
    d = this.ToValue(Coin.Kr20);
    Assert.AreEqual<decimal>(20M, d);
}
    }
}
