// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Explorable;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace VendingMachine.Data
{
    public partial class ProductTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ProductTest))]
public void Equals01573()
{
    Product product;
    bool b;
    product = PexInvariant.CreateInstance<Product>();
    PexInvariant.SetField<string>
        ((object)product, "<Name>k__BackingField", (string)null);
    PexInvariant.SetField<int>((object)product, "<Ammount>k__BackingField", 0);
    PexInvariant.SetField<decimal>
        ((object)product, "<Price>k__BackingField", default(decimal));
    PexInvariant.CheckInvariant((object)product);
    b = this.Equals01(product, (object)null);
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)product);
    Assert.AreEqual<string>((string)null, product.Name);
    Assert.AreEqual<int>(0, product.Ammount);
    Assert.AreEqual<decimal>(default(decimal), product.Price);
}
[TestMethod]
[PexGeneratedBy(typeof(ProductTest))]
[ExpectedException(typeof(NullReferenceException))]
public void Equals01ThrowsNullReferenceException295()
{
    Product product;
    bool b;
    product = PexInvariant.CreateInstance<Product>();
    PexInvariant.SetField<string>
        ((object)product, "<Name>k__BackingField", (string)null);
    PexInvariant.SetField<int>((object)product, "<Ammount>k__BackingField", 0);
    PexInvariant.SetField<decimal>
        ((object)product, "<Price>k__BackingField", default(decimal));
    PexInvariant.CheckInvariant((object)product);
    b = this.Equals01(product, (object)product);
}
[TestMethod]
[PexGeneratedBy(typeof(ProductTest))]
public void Equals01413()
{
    Product product;
    bool b;
    product = PexInvariant.CreateInstance<Product>();
    PexInvariant.SetField<string>((object)product, "<Name>k__BackingField", "");
    PexInvariant.SetField<int>((object)product, "<Ammount>k__BackingField", 0);
    PexInvariant.SetField<decimal>
        ((object)product, "<Price>k__BackingField", default(decimal));
    PexInvariant.CheckInvariant((object)product);
    b = this.Equals01(product, (object)product);
    Assert.AreEqual<bool>(true, b);
    Assert.IsNotNull((object)product);
    Assert.AreEqual<string>("", product.Name);
    Assert.AreEqual<int>(0, product.Ammount);
    Assert.AreEqual<decimal>(default(decimal), product.Price);
}
    }
}
