// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using VendingMachine.Data;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace VendingMachine.Stock
{
    public partial class CoinManagerTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CoinManagerTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void EjectCoinThrowsContractException906()
{
    try
    {
      CoinManager coinManager;
      coinManager = new CoinManager();
      this.EjectCoin(coinManager, Coin.Ore50, 0, (LinkedList<Coin>)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(CoinManagerTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void EjectCoinThrowsContractException365()
{
    try
    {
      CoinManager coinManager;
      LinkedList<Coin> linkedList;
      coinManager = new CoinManager();
      Coin[] @is = new Coin[0];
      linkedList = new LinkedList<Coin>((IEnumerable<Coin>)@is);
      this.EjectCoin(coinManager, Coin.Ore50, 0, linkedList);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(CoinManagerTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void EjectCoinThrowsContractException998()
{
    try
    {
      CoinManager coinManager;
      LinkedList<Coin> linkedList;
      coinManager = new CoinManager();
      Coin[] @is = new Coin[3];
      linkedList = new LinkedList<Coin>((IEnumerable<Coin>)@is);
      this.EjectCoin(coinManager, Coin.Ore50, 0, linkedList);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(CoinManagerTest))]
public void EjectCoin685()
{
    CoinManager coinManager;
    LinkedList<Coin> linkedList;
    coinManager = new CoinManager();
    Coin[] @is = new Coin[3];
    linkedList = new LinkedList<Coin>((IEnumerable<Coin>)@is);
    this.EjectCoin(coinManager, Coin.Ore50, 1, linkedList);
    Assert.IsNotNull((object)coinManager);
}
    }
}
